version: '3.9'

services:
  springboot:
    restart: "always"
    container_name: springboot
    build: 
      context: ./backend/spring-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    restart: "always"
    image: mysql:latest
    container_name: database
    # 공식 문서를 보고 환경 설정 변수 확인
    environment: 
      - MYSQL_ROOT_PASSWORDt${PASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "3306:3306"
