version: '3.9'

services:
  springboot:
    restart: "always"
    container_name: springboot
    build:
      context: ./backend/spring-server
      dockerfile: Dockerfile
    ports:
      - "9999:9999"

  vite:
    restart: "always"
    container_name: vite-container
    build:
      context: ./piyou-info
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
